import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import Footer from "./components/footer";
import RecoilRootWrapper from "./recoilRootWrapper";
import { Toaster } from "react-hot-toast";
import { CustomFlowbiteTheme, Flowbite } from "flowbite-react";
import { HelpBot } from "./components/helpBot/helpBot";

const poppin = Poppins({ 
  weight: '400',
  subsets: ['latin'] ,
})

const customTheme: CustomFlowbiteTheme = {
  modal: {
      content: {
          "inner": "rounded-3xl bg-white"
      }
  }
}

export const metadata: Metadata = {
  title: "Tech ShopV2.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppin.className}>
      <Flowbite theme={{ theme: customTheme }}>
        <RecoilRootWrapper>
          <Toaster position="top-center" />
          <Navbar/>
            {children}
            <HelpBot/>
          <Footer/>
        </RecoilRootWrapper>
        </Flowbite>
        </body>
    </html>
  );
}
